language: python
env:
  global:
    secure: KGi+/IohSIlNzxDWmiorSHQNO4VSiid6H2G1eQ0OeYqP4g/veQtlufwAKFOKFApSuLJOG180sFIK5h/ZpKbP+8enz50/bX1NOfZ9FJoxLeyw57ux406eQtQVsyHPjeYPfTk9i8LUqZzxKyZeMz6fnSclDXPwbzldolhbagyqSkU=
install:
- pip install -r requirements.txt
script:
- ansible-playbook -i 127.0.0.1, -c local -s -e ssh_user=travis -e hostname=travis-tmp-host.demo.modcloth.com
  -vvvv ./example.yml
before_install:
- curl -L -s -o files/sumo.deb $SUMOLOGIC_DEB_LOCATION
