language: python
env:
  global:
  - NETWORK_ENV=demo
  - ROLE=travis
  - TEAM=platform
install:
- pip install -r requirements.txt
script:
- ansible-playbook -i 127.0.0.1, -c local -s -e ssh_user=travis -e hostname=travis-tmp-host.demo.modcloth.com
  -vvvv ./example.yml
before_install:
- openssl aes-256-cbc -K $encrypted_60885b5e13fd_key -iv $encrypted_60885b5e13fd_iv
  -in sumo.deb.enc -out files/sumo.deb -d
