---
- name: 'check if sumologic is installed'
  command: dpkg-query -l sumocollector
  register: sumologic_collector_deb_check
  failed_when: no
- name: 'copy collector installer'
  copy:
    src='{{ sumologic_installer_file }}'
    dest='{{ sumologic_installer_remote_file }}'
  when: sumologic_collector_deb_check.rc == 1
- name: 'run collector installer'
  apt: deb='{{ sumologic_installer_remote_file }}'
  when: sumologic_collector_deb_check.rc == 1
- name: 'add collector configuration'
  template:
    src=sumo.conf.j2
    dest=/etc/sumo.conf
  register: sumologic_collector_add_configuration
- name: 'add collector sources configuration'
  template:
    src='{{ sumologic_collector_source_template }}'
    dest=/etc/sumo-sources.json
  register: sumologic_collector_add_sources_configuration
  when: sumologic_collector_source_template is defined
- name: 'restart collector'
  service:
    name=collector
    state=restarted
  when:  sumologic_collector_add_configuration|changed
         or sumologic_collector_add_sources_configuration|changed
